/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatWindow: typeof import('./src/components/ChatWindow.vue')['default']
    ChatWindows: typeof import('./src/components/ChatWindows.vue')['default']
    ProfileCard: typeof import('./src/components/ProfileCard.vue')['default']
  }
}
